server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_microservice
    username: sujit
    password: Pass@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect